---
- name: KMC Windows Server Information
  hosts: Windows
  gather_facts: no

  tasks:
    - name: Ping
      ansible.windows.win_ping:

    - name: Get the hostname using win_shell
      ansible.windows.win_shell: hostname
      register: hostname_result

    - name: Show the hostname
      ansible.builtin.debug:
        var: hostname_result.stdout