---
- name: KMC Windows Server Information
  hosts: Windows
  gather_facts: no

  tasks:
    - name: Ping
      ansible.windows.win_ping:

    - name: Get ComputerName via PowerShell
      ansible.windows.win_shell: |
        $env:COMPUTERNAME
      register: computer_name

    - debug:
        var: computer_name.stdout