- name: KMC Windows Server Information
  hosts: Windows
  gather_facts: 'no'

  tasks:
    - name: Ping Windows
      ansible.windows.win_ping:

    - name: Show Hostname
      ansible.windows.win_powershell:
        script: |
          Write-Output "HELLO_WORLD"
      register: computer_info

    - debug:
        var: computer_info.output