---
- name: KMC Windows Server Information
  hosts: Windows
  gather_facts: no

  tasks:
    - name: Ping Servers
      ansible.windows.win_ping:

    - name: Get Hostname
      ansible.windows.win_command: hostname
      register: hostname_out