---
- name: KMC Windows Server Information
  hosts: Windows
  gather_facts: no

  tasks:
    - name: Ping
      ansible.windows.win_ping:

    - name: Get Hostname
      ansible.windows.win_command: hostname
      register: hostname_out

    - name: Show Hostname
      ansible.builtin.debug:
        var: hostname_out.stdout