---
- name: KMC Windows Server Information
  hosts: Windows
  gather_facts: no

  tasks:
    - name: Ping Windows
      ansible.windows.win_ping:

    - name: Get computer info via win_powershell
      ansible.windows.win_powershell:
        script: |
          Get-ComputerInfo | Select-Object CsName, OsName
      register: computer_info

    - name: Show computer info
      ansible.builtin.debug:
        var: computer_info.output